crypto_list: ['Polkadot','Bitcoincash','cardano','XRP','litecoin','Stellar','Monero','solana','dogecoin','Avax','Chainlink',
      'polygonnetwork', 'EthereumClassic','terraluna','stacks', 'Tronix', 'dashpay', 'UniSwap','SHIBArmy', 'Bitcoin','ethereum']
